[book]
authors = ["MixBadGun"]
language = "zh"
multilingual = false
src = "src"
title = "音MAD活动：LIVE"

[preprocessor.theme]
pagetoc = true

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]