[book]
authors = ["MixBadGun"]
language = "en"
multilingual = false
src = "src"
title = "音MAD活动：MIX"

[preprocessor.theme]
pagetoc = true

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]
